//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_AverageColors_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_AverageColors_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_ColorSet_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_ColorSet_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_FromName_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_FromName_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_FromOle_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_FromOle_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_Gradient_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_Gradient_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_Invert_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_Invert_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_Logo_24 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_Logo_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_Palette_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_Palette_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_Preview_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_Preview_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_ToHex_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_ToHex_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_ToOle_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_ToOle_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorPlus_TweenColors2_01 {
            get {
                object obj = ResourceManager.GetObject("ColorPlus_TweenColors2_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 190,189,127
        ///194,176,120
        ///198,166,100
        ///229,190,1
        ///205,164,52
        ///169,131,7
        ///228,160,16
        ///220,157,0
        ///138,102,66
        ///199,180,70
        ///238,234,205
        ///225,204,79
        ///230,214,144
        ///237,255,33
        ///245,208,51
        ///248,243,43
        ///158,151,100
        ///153,153,80
        ///243,218,11
        ///250,210,1
        ///174,160,75
        ///255,255,0
        ///157,145,1
        ///244,169,0
        ///214,174,1
        ///243,165,5
        ///239,169,74
        ///106,93,77
        ///112,83,53
        ///243,159,24
        ///237,118,14
        ///201,60,32
        ///203,40,33
        ///255,117,20
        ///244,70,17
        ///255,35,1
        ///255,164,32
        ///247,94,37
        ///245,64,33
        ///216,75,32
        ///236,124,38
        ///229,81,55
        ///195,88,49
        ///175,43,30
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RAL_Colors {
            get {
                return ResourceManager.GetString("RAL_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///1001
        ///1002
        ///1003
        ///1004
        ///1005
        ///1006
        ///1007
        ///1011
        ///1012
        ///1013
        ///1014
        ///1015
        ///1016
        ///1017
        ///1018
        ///1019
        ///1020
        ///1021
        ///1023
        ///1024
        ///1026
        ///1027
        ///1028
        ///1032
        ///1033
        ///1034
        ///1035
        ///1036
        ///1037
        ///2000
        ///2001
        ///2002
        ///2003
        ///2004
        ///2005
        ///2007
        ///2008
        ///2009
        ///2010
        ///2011
        ///2012
        ///2013
        ///3000
        ///3001
        ///3002
        ///3003
        ///3004
        ///3005
        ///3007
        ///3009
        ///3011
        ///3012
        ///3013
        ///3014
        ///3015
        ///3016
        ///3017
        ///3018
        ///3020
        ///3022
        ///3024
        ///3026
        ///3027
        ///3028
        ///3031
        ///3032
        ///3033
        ///4001
        ///4002
        ///4003
        ///4004
        ///4005
        ///4006
        ///4007
        ///4008
        ///4009
        ///4010
        ///4011
        ///4012
        ///5000
        ///5001
        ///5002
        ///5003
        ///5004
        ///50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RAL_Indices {
            get {
                return ResourceManager.GetString("RAL_Indices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Beige
        ///Beige
        ///Sand Yellow
        ///Signal Yellow
        ///Golden Yellow
        ///Honey Yellow
        ///Maize Yellow
        ///Daffodil Yellow
        ///Brown Beige
        ///Lemon Yellow
        ///Oyster White
        ///Ivory
        ///Light Ivory
        ///Sulfur Yellow
        ///Saffron Yellow
        ///Zinc Yellow
        ///Grey Beige
        ///Olive Yellow
        ///Colza Yellow
        ///Traffic Yellow
        ///Ochre Yellow
        ///Luminous Yellow
        ///Curry
        ///Melon Yellow
        ///Broom Yellow
        ///Dahlia Yellow
        ///Pastel Yellow
        ///Pearl Beige
        ///Pearl Gold
        ///Sun Yellow
        ///Yellow Orange
        ///Red Orange
        ///Vermilion
        ///Pastel Orange
        ///Pure Orange
        ///Luminous Orange
        ///Luminous Bright Orange
        ///Bri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RAL_Names {
            get {
                return ResourceManager.GetString("RAL_Names", resourceCulture);
            }
        }
    }
}
